addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.2.0")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.2.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "1.10.1")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.4.3")
addSbtPlugin("nl.gn0s1s"          % "sbt-dotenv"                    % "3.0.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"                  % "2.3.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"                 % "1.9.2")
addSbtPlugin("org.scalastyle"    %% "scalastyle-sbt-plugin"         % "1.0.0")
