name: Native Tests
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: coursier/cache-action@v6.3
      - name: Setup Scala CLI
        uses: VirtusLab/scala-cli-setup@main
      - name: Test
        run: make test-native
